name: Terraform GitOps Workflow
run-name: TerraformCD

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure-tf/**'
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    paths:
      - 'infrastructure-tf/**'
  workflow_dispatch:
    inputs:
      TF_LOG:
        description: "Run Terraform in log mode"
        required: true
        type: choice
        options:
          - "DEBUG"
          - "INFO"
          - "WARN"
          - "ERROR"
        default: "INFO"

env:
  TF_VERSION: "1.5.7"
  AWS_REGION: "us-east-1"

jobs:
  setup-runner:
    runs-on: self-hosted
    steps:
      - name: Install Git
        run: |
          sudo yum update -y
          sudo yum install git -y

      - name: Verify Git Installation
        run: git --version

      - name: Install Docker
        run: |
          sudo yum update -y
          sudo yum install docker -y
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          sudo chmod 666 /var/run/docker.sock

      - name: Verify Docker Installation
        run: docker --version

  terraform-plan:
    needs: setup-runner
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Terraform Init
        working-directory: infrastructure-tf
        run: terraform init

      - name: Terraform Plan
        working-directory: infrastructure-tf
        run: terraform plan -out=tfplan -input=false
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          TF_LOG: ${{ inputs.TF_LOG }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: infrastructure-tf/tfplan

  manual-approval:
    needs: terraform-plan
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GH_PAT }}
          approvers: ${{ vars.APPROVALS }}
          minimum-approvals: 1
          issue-title: "Terraform Apply Approval Request"
          issue-body: "Please approve or deny the terraform apply command"

  terraform-apply:
    needs: manual-approval
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Apply
        working-directory: infrastructure-tf
        run: terraform apply -input=false tfplan
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          TF_LOG: ${{ inputs.TF_LOG }}
