name: Terraform GitOps Workflow
run-name: TerraformCD

on:
  push:
    paths:
      - 'infrastructure-tf/**' # Trigger only when changes occur in this folder
  workflow_dispatch: # Allow manual trigger
    inputs:
      TF_LOG:
        description: "Run Terraform in log mode"
        required: true
        type: choice
        options:
          - "DEBUG"
          - "INFO"
          - "WARN"
          - "ERROR"
        default: "INFO"

env:
  TF_VERSION: "1.5.7"
  AWS_REGION: "us-east-1"

jobs:
  terraform-plan:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Docker
        run: |
          sudo yum update -y
          sudo yum install docker -y
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          newgrp docker

      - name: Install Git
        run: |
          sudo yum update -y
          sudo yum install git -y
          git --version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: infrastructure-tf
        run: terraform init

      - name: Terraform Plan
        working-directory: infrastructure-tf
        run: terraform plan -out=tfplan -input=false
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          TF_LOG: ${{ inputs.TF_LOG }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: infrastructure-tf/tfplan
          retention-days: 7

  manual-approval:
    needs: terraform-plan
    runs-on: self-hosted
    steps:
      - name: Set Docker
        run: |
          sudo yum update -y
          sudo yum install docker -y
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          newgrp docker

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TERRAFORM_SECRET }}
          approvers: ${{ vars.APPROVALS }}
          minimum-approvals: 1
          issue-title: "Terraform Apply Approval Request"
          issue-body: "Please approve or deny the terraform apply command"

  terraform-apply:
    needs: manual-approval
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Set Docker
        run: |
          sudo yum update -y
          sudo yum install docker -y
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          newgrp docker

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan

      - name: Install Git
        run: |
          sudo yum update -y
          sudo yum install git -y
          git --version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          TF_LOG: ${{ inputs.TF_LOG }}

      - name: Terraform Apply
        working-directory: infrastructure-tf
        run: terraform apply -input=false tfplan
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
